exports.getTorrents = {
  'd.get_hash=': 'infohash',
  'd.is_open=': 'is_open',
  'd.is_hash_checking=': 'is_hash_checking',
  'd.is_hash_checked=': 'is_hash_checked',
  'd.get_state=': 'state',
  'd.get_name=': 'name',
  'd.get_size_bytes=': 'bytes_total',
  'd.get_completed_chunks=': 'num_chunks_downloaded',
  'd.get_size_chunks=': 'num_chunks',
  'd.get_bytes_done=': 'bytes_downloaded',
  'd.get_up_total=': 'bytes_uploaded',
  'd.get_ratio=': 'ratio',
  'd.get_up_rate=': 'upload_speed',
  'd.get_down_rate=': 'download_speed',
  'd.get_chunk_size=': 'chunk_size',
  'd.get_custom1=': 'd.get_custom1=',
  'd.get_peers_accounted=': 'peers',
  'd.get_peers_not_connected=': 'd.get_peers_not_connected=',
  'd.get_peers_connected=': 'd.get_peers_connected=',
  'd.get_peers_complete=': 'seeders',
  'd.get_left_bytes=': 'bytes_remaining',
  'd.get_priority=': 'd.get_priority=',
  'd.get_state_changed=': 'd.get_state_changed=',
  'd.get_skip_total=': 'd.get_skip_total=',
  'd.get_hashing=': 'd.get_hashing=',
  'd.get_chunks_hashed=': 'd.get_chunks_hashed=',
  'd.get_base_path=': 'path',
  'd.get_creation_date=': 'created_at',
  'd.get_tracker_focus=': 'd.get_tracker_focus=',
  'd.is_active=': 'is_active',
  'd.get_message=': 'd.get_message=',
  'd.get_custom2=': 'd.get_custom2=',
  'd.get_free_diskspace=': 'free_disk_space',
  'd.is_private=': 'is_private',
  'd.is_multi_file=': 'is_multifile'
}

exports.getTorrentDetails = {
  'f.get_completed_chunks=': 'f.get_completed_chunks=',
  'f.get_frozen_path=': 'f.get_frozen_path=',
  'f.get_last_touched=': 'f.get_last_touched=',
  'f.get_match_depth_next=': 'f.get_match_depth_next=',
  'f.get_match_depth_prev=': 'f.get_match_depth_prev=',
  'f.get_offset=': 'f.get_offset=',
  'f.get_path=': 'f.get_path=',
  'f.get_path_components=': 'f.get_path_components=',
  'f.get_path_depth=': 'f.get_path_depth=',
  'f.get_priority=': 'f.get_priority=',
  'f.get_range_first=': 'f.get_range_first=',
  'f.get_range_second=': 'f.get_range_second=',
  'f.get_size_bytes=': 'f.get_size_bytes=',
  'f.get_size_chunks=': 'f.get_size_chunks=',
  'f.is_create_queued=': 'f.is_create_queued=',
  'f.is_created=': 'f.is_created=',
  'f.is_open=': 'f.is_open=',
  'f.is_resize_queued=': 'f.is_resize_queued=',
  
  't.get_group=': 't.get_group=',
  't.get_id=': 't.get_id=',
  't.get_min_interval=': 't.get_min_interval=',
  't.get_normal_interval=': 't.get_normal_interval=',
  't.get_scrape_complete=': 'num_complete_peers',
  't.get_scrape_downloaded=': 't.get_scrape_downloaded=',
  't.get_scrape_incomplete=': 'num_incomplete_peers',
  't.get_scrape_time_last=': 'last_scrape_at',
  't.get_type=': 'protocol',
  't.get_url=': 'url',
  't.is_enabled=': 'is_enabled',
  't.is_open=': 'is_open'
}

exports.getStats = {
  'get_up_total': 'upload_total',
  'get_down_total': 'download_total',
  'get_upload_rate': 'upload_rate_max',
  'get_download_rate': 'download_rate_max',
  'get_up_rate': 'upload_rate',
  'get_down_rate': 'download_rate',
  'get_safe_free_diskspace': 'free_disk_space'
}
