exports.getTorrents = {
  'd.get_hash=': 'infohash',
  'd.is_open=': 'is_open',
  'd.is_hash_checking=': 'd.is_hash_checking=',
  'd.is_hash_checked=': 'd.is_hash_checked=',
  'd.get_state=': 'state',
  'd.get_name=': 'name',
  'd.get_size_bytes=': 'bytes_total',
  'd.get_completed_chunks=': 'num_chunks_downloaded',
  'd.get_size_chunks=': 'num_chunks',
  'd.get_bytes_done=': 'bytes_downloaded',
  'd.get_up_total=': 'bytes_uploaded',
  'd.get_ratio=': 'ratio',
  'd.get_up_rate=': 'upload_speed',
  'd.get_down_rate=': 'download_speed',
  'd.get_chunk_size=': 'chunk_size',
  'd.get_custom1=': 'd.get_custom1=',
  'd.get_peers_accounted=': 'peers',
  'd.get_peers_not_connected=': 'd.get_peers_not_connected=',
  'd.get_peers_connected=': 'd.get_peers_connected=',
  'd.get_peers_complete=': 'seeders',
  'd.get_left_bytes=': 'bytes_remaining',
  'd.get_priority=': 'd.get_priority=',
  'd.get_state_changed=': 'd.get_state_changed=',
  'd.get_skip_total=': 'd.get_skip_total=',
  'd.get_hashing=': 'd.get_hashing=',
  'd.get_chunks_hashed=': 'd.get_chunks_hashed=',
  'd.get_base_path=': 'path',
  'd.get_creation_date=': 'created_at',
  'd.get_tracker_focus=': 'd.get_tracker_focus=',
  'd.is_active=': 'is_active',
  'd.get_message=': 'd.get_message=',
  'd.get_custom2=': 'd.get_custom2=',
  'd.get_free_diskspace=': 'free_disk_space',
  'd.is_private=': 'is_private',
  'd.is_multi_file=': 'is_multifile'
}

exports.getTorrent = {
  'f.get_completed_chunks=': 'f.get_completed_chunks=',
  'f.get_frozen_path=': 'f.get_frozen_path=',
  'f.get_last_touched=': 'f.get_last_touched=',
  'f.get_match_depth_next=': 'f.get_match_depth_next=',
  'f.get_match_depth_prev=': 'f.get_match_depth_prev=',
  'f.get_offset=': 'f.get_offset=',
  'f.get_path=': 'f.get_path=',
  'f.get_path_components=': 'f.get_path_components=',
  'f.get_path_depth=': 'f.get_path_depth=',
  'f.get_priority=': 'f.get_priority=',
  'f.get_range_first=': 'f.get_range_first=',
  'f.get_range_second=': 'f.get_range_second=',
  'f.get_size_bytes=': 'f.get_size_bytes=',
  'f.get_size_chunks=': 'f.get_size_chunks=',
  'f.is_create_queued=': 'f.is_create_queued=',
  'f.is_created=': 'f.is_created=',
  'f.is_open=': 'f.is_open=',
  'f.is_resize_queued=': 'f.is_resize_queued='
}
